version: '3.7'
services:
   geode:
     hostname: geode
     container_name: geode
     image: apachegeode/geode
     platform: linux/amd64
     tty: true
     privileged: true
     ports:
       - '1099:1099'
       - '10331:10331'
       - '10334:10334'
       - '41001:41001'
       - '40404:40404'
       - '7575:7575'
       - '7070:7070'
     volumes:
       - ./geode:/scripts
     command: /scripts/startLocator.sh
